server:
  shutdown: graceful
  port: 8090

spring:
  application:
    name: coupon
  datasource:
    url: jdbc:postgresql://localhost:5432/coupon
    username: myuser
    password: secret
  docker:
    compose:
      enabled: false # Enable if you use Docker Compose - I use Podman Compose
  kafka:
    bootstrap-servers:
      - localhost:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  threads:
    virtual:
      enabled: true
